### ISSUE TITLE
Support for complex multi-field logins

### ISSUE THREAD

**Issue by webjames** [bitwarden/core#11]
Some websites logins require other details beyond a username and password. This might include company/account etc. 

It would be great to have autofill and auto capture support for this type of form. 
An example of such a form is available here:
https://sc3.omniture.com/login/

**Comment by kspearrin** [comment]
This would be nice to add. In the meantime you can just store them as notes to the site if it is something you need to remember.

**Comment by kspearrin** [comment]
This is mostly now available as custom fields.

----

We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
