### ISSUE TITLE
Bitwarden support for Raspberry Pi / Odroid HC-1 - Docker Solution with less ressources or Nextcloud Integration

### ISSUE THREAD

**Issue by ChriKn** [bitwarden/core#122]
As told in the title, the actual Docker solution requires some impressives ressources (4 GB of RAM) which seem a bit odd for a password management tool (speaking of a single-user-scenario of course). 
Tools like Nextcloud use up far less ressources while in Docker mode and provide solutions for plugins as an exemple.

Would it theoretically be possible to reduce the footprint of the docker module to work side by side with, let's say, a Nextcloud module on a Raspberry or even better an Odroid HC-1  which was really made for this scenario : https://magazine.odroid.com/article/odroid-hc1-and-odroid-mc1/ ?

Another solution could be a Nextcloud integration, effectly bringing bitwarden to a pretty huge community which already works around the principles of open-source / self-hostable software.

**Comment by kspearrin** [comment]
The self hosted solution we have today is basically a bundled version of exactly what we run the public bitwarden cloud with. This solution supports a very large amount of users and traffic and is definitely not optimized for use cases with a single user (or even several users).

The ram requirement is not really a side effect of docker, but from our database engine, sql server.

Maybe one day when we have the resources to fork the codebase (i.e database) to support multiple scenarios this can become a thing. For now though, it’s not really possible.

**Comment by ChriKn** [comment]
Thanks for the fast heads-up. This would indeed be great and probably bring some notoriety to the project, as self-hosting seems like a major selling point for your software.
Hope to be there when it happens !

**Comment by kspearrin** [comment]
It seems in the next cumulative update for sql server on docker they are lowering the memory requirements to 2 GB. See https://github.com/Microsoft/mssql-docker/issues/114#issuecomment-332976038

**Comment by OhjeezwhathaveIdone** [comment]
@ChriKn indeed the ability to self host, at least for me, is the major selling point in Bitwarden as I'm not satisfied with the current syncing method in KeePass between Desktop and iOS as explained [here](https://github.com/bitwarden/mobile/issues/164#issue-272138135) and I wish to keep control of my data.  Not to forget that there isn't an official KeePass application for iOS.  I feel that these three issues combined is the reason why self hosting Bitwarden seems so appealing especially for single users/households.

With the increase in commonality of IoT devices and other services designed for them, PiHole is an example that springs to mind, I couldn't think of a better use case of such a device than Bitwarden and therefore I echo your comments however the down side of those is the limitation in RAM.  Whilst I wouldn't be hosting it on such a device the memory I have to spare is extremely sparse and any reduction benefits me greatly.

I was going to update you with the information about Microsoft seeking to reduce the RAM requirement, so that I could share the excitement that I have of the news with you, however @kspearrin has beat me to it after I had posted it [here](https://github.com/bitwarden/core/issues/110#issuecomment-342785017).

**Comment by ChriKn** [comment]
@kspearrin @OhjeezwhathaveIdone 
There is allready a Password management solution for nextcloud : https://github.com/nextcloud/passman
Maybe some collaboration could help bind the synergies and bring this thing to a closer reality ?
Even with a 2 GB minimum (which would be great) I don't see myself buying another Odroid just to handle my passwords and get into a difficult docker swarm scenario...

**Comment by shazow** [comment]
I just read [this article](https://jcs.org/2017/11/17/bitwarden) where the author wrote his own API backend by reverse engineering the default API.

It's written in Ruby and [the spec is fairly well documented](https://github.com/jcs/bitwarden-ruby/blob/master/API.md) if anyone wants to make their own: https://github.com/jcs/bitwarden-ruby

**Comment by efuquen** [comment]
Was really excited about this project until I learned about this limitation when trying to run it on 512 MB DO droplet. It just doesn't make sense to pay $40 a month for a higher memory instance I wouldn't need otherwise just for a password manager.

I don't know much C#, but I dug enough to see that the .NET native SQL libraries, predictably, ties you in to SqlServer. Does not give me hope that any change to allow this to use a database with more sane memory requirements will come easily or any time soon.

**Comment by sorcer1122** [comment]
I am also struggling to run it on my 2Gb machine, so look forward for updates as well. Is there any chance to use a different SQL backend? PostgreSQL?

**Comment by twright-msft** [comment]
As of SQL Server 2017 CU2 the minimum memory requirement has been lowered to 2 GB for the mssql-server-linux container image.

**Comment by sorcer1122** [comment]
@twright-msft has this CU2 update been rolled out already by bitwarden?

**Comment by twright-msft** [comment]
@sorcer1122  Sorry, that I don't know.  Somebody from the bitwarden team would need to comment on that.

**Comment by kspearrin** [comment]
CU2 will be rolled out next week.

**Comment by kspearrin** [comment]
v1.15.1 is now live with mssql CU2. RAM requirements for bitwarden are now 2GB.

**Comment by sorcer1122** [comment]
Thanks a lot @kspearrin ! I am now able to run mssql without any issues.

**Comment by ChriKn** [comment]
Does Bitwarden fully use the 2GB or would it be possible to limit docker to using 512 MB or 1 GB

**Comment by sorcer1122** [comment]
@ChriKn nope, on my system the usage is 1.7Gb (bitwarden + other apps)

**Comment by ChriKn** [comment]
@sorcer1122 I am using an Odroid HC1 with Nextcloudpi on it. Do you think a Bitwarden Docker would still work on it or would it eat up all the ressources ?
Thanks for your help !

**Comment by sorcer1122** [comment]
@ChriKn Unfortunately, I have got no clue. If you have got 2Gb+ RAM - should be fine.

**Comment by ChriKn** [comment]
@sorcer1122 It  has 2Gb of RAM... I will try and report back !
Thanks all !

**Comment by Pschittt** [comment]
Hello, 
@ChriKn, so it works ? :)

**Comment by RenonDis** [comment]
@ChriKn up !

**Comment by ChriKn** [comment]
Sadly it doesn't as the odroid isn't arm64 and by the time I looked at it
bitwarden only worked on arm64.

RenonDis <notifications@github.com> schrieb am Mo., 5. März 2018, 12:55:

**Comment by RenonDis** [comment]
@ChriKn That's a fast answer! So you're staying with Nextcloud passman ?

**Comment by ChriKn** [comment]
I have gone with the standard Bitwarden for the moment (I trust them enough
if they open the possibility to self host) and will come back to this when
I have more time or the need for a bigger server (or find another solution)

RenonDis <notifications@github.com> schrieb am Mo., 5. März 2018, 12:59:

**Comment by kspearrin** [comment]
Things are much better now with the lower RAM requirements of SQL Server.

------------------

We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
