### ISSUE TITLE
auditing login history and kill active sessions

### ISSUE THREAD

**Issue by jawz101** [bitwarden/core#124]
It'd be nice to be able to see when my master password login has been used, which IP address/location, device used it.  Ability to destroy logged in sessions.
And I've already mentioned geoip blocking.

As it stands this is still a password manager but there should be more control of your access than just reliance on the authentication.  Pretend someone has your credentials or you leave a browser unlocked.  You have no control to end their session.

**Comment by kspearrin** [comment]
In the web vault there is an option to de-authorize all sessions under settings.

**Comment by jawz101** [comment]
Ah... thanks.
Still, could there be some sort of way to see "Someone in Ireland logged into my vault."  That would be nice to see an audit trail for X days.

**Comment by kspearrin** [comment]
We have plans for more audit logging in the future, yes.

**Comment by jungle-boogie** [comment]
Looking forward to the improvements, @kspearrin.

**Comment by kspearrin** [comment]
This is now available for enterprise organizations. It is still planned for premium users, though no timeline exists for that yet.

**Comment by jawz101** [comment]
I hope it's considered fundamental for a hosted password manager for any user.  I'd break out the free vs. premium model on something like anything under 100 stored accounts is free.  This just feels like a basic necessity for a hosted solution.

**Comment by jungle-boogie** [comment]
Looking forward to this being available in premium accounts. Why would a timeline not yet exist? Don't you already have a working implementation?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/account-access-history/118

This issue will now be closed. Thanks!

**Comment by albin1997536** [comment]
i second this
