### ISSUE TITLE
Extend deletion limit

### ISSUE THREAD

**Issue by jwillmer** [bitwarden/core#136]
I imported my passwords and found a lot of old ones. I like to delete all imported passwords, clean up my import file and import it again. 

Deleting the 5xx stored passwords displays: **"An error occurred"**
In the network tab of the debugging I find this message:
```
{"Message":"The model state is invalid.","ValidationErrors":{"":["You can only delete up to 200 items at a time."]},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Object":"error"}
```

Please extend the limit - why have one? Or create a meaningful error message as well as an option to delete the first 200 of the selected passwords.

**Comment by kspearrin** [comment]
Yes, that error message should definitely be better. We can also raise the limit to something 500.

**Comment by jwillmer** [comment]
Why have a limit in the first place?

**Comment by jeroen7s** [comment]
@jwillmer before the removal of the limit, there should definitely be an added trashcan functionality, so it's still recoverable if there happens to be a critical entry in there that's accidentally removed

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
