### ISSUE TITLE
Feature Request: Add more "Types" of data

### ISSUE THREAD

**Issue by erousr** [bitwarden/core#150]
It would be great to have more pre-defined Types, or why not ability to create your own Types?

Take 1Password for example, there you have the ability to create:
Bank Account, Passport, Driver License, Membership, Rewardprogram, Account, Email Account, Server, Router, Database, FTP Account, Software License, Generic Account and much more...

Wallet Items:
![screenshot 1](https://user-images.githubusercontent.com/13121758/33481291-252613b6-d694-11e7-942e-1ccc8069d675.jpg)

Accounts:
![screenshot 2](https://user-images.githubusercontent.com/13121758/33481293-25449fe8-d694-11e7-8d80-0ab64fde1d72.jpg)

**Comment by 3v1n0** [comment]
Also importing from LastPass there are various generic types which are not imported.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
