### ISSUE TITLE
Feature Request: Be able to duplicate items.

### ISSUE THREAD

**Issue by erousr** [bitwarden/core#151]
I woulud love to be able to duplicate an item. For instance if you are creating a new credit card, it would improve the time it takes greatly by already having the custom fields etc from your previous card when you start.

**Comment by NicerGit** [comment]
I couldn't agree more!
On a tangential subject, it would also be great for identity items to come with preconfigured fields, including bank account, credit card etc, a la Roboform.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/duplicate-an-existing-item-in-vault/150

This issue will now be closed. Thanks!
