### ISSUE TITLE
Add increasing timeouts on login failure

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/core#16]
Currently there is about a 2 second timeout on login failure. I'd recommend using an increasing timeout based on IP address that prevents too many failed logins, and requires the user to wait 5 minutes after too many failed attempts. This is an important feature for a site that will host user passwords.

**Comment by kspearrin** [comment]
This was meant to be a temporary solution. I'll probably be adding rate limiting across the board for all APIs pretty soon to prevent abuse. The auth APIs will have strict limits to prevent brute force.

**Comment by benrubson** [comment]
Perhaps we could also think about an external log which would contain failed accesses ?
We would then be able to ban bad IPs at host firewall level, using for example Fail2Ban.

As suggested in other apps, the following pattern could be used, as per [this Fail2Ban PR](https://github.com/fail2ban/fail2ban/pull/1646) :
`user \S* ?(not found|not authorized|password mismatch|sent invalid token|misbehaved|tried to break-in): .+`

For example :
`error_log("user sent invalid token: Bitwarden");`
`error_log("user bob not found: Bitwarden");`
`error_log("user admin password mismatch: Bitwarden");`

**Comment by kspearrin** [comment]
@benreyn Enterprise organizations already have access failure audit logs for their users.

**Comment by benrubson** [comment]
Thx @kspearrin for your answer.
Is this log available to the host system through a flat file which could easily be parsed by an external tool (such as Fail2Ban then) ?

**Comment by kspearrin** [comment]
It exists in the database Events table.

**Comment by benrubson** [comment]
Thank you Kyle.
It would really be interesting to have it as a plain text file so that Fail2ban can easily be plugged to it.
This log file should not contain only failures for existing users, but every failure (wrong user, wrong password, wrong token...) made from any IP.
In addition if the log entries can match the above regex, then it would really be perfect.
Bitwarden would then be Fail2ban ready 👍 
Thank you again !

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
