### ISSUE TITLE
Add an expiration date to passwords?

### ISSUE THREAD

**Issue by honestserpent** [bitwarden/core#163]
Wouldn't it be cool if there was an option to set an expiration date (or, even better, a time period) on passwords? Something like "3 months", and in 3 months, a notification will be sent that you should change the password.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/password-expiration-date/162

This issue will now be closed. Thanks!
