### ISSUE TITLE
Support the additional use of a keyfile [feature request]

### ISSUE THREAD

**Issue by msrv** [bitwarden/core#178]
Dear @kspearrin, 

thank you for your great work on bitwarden. I have a suggestion: Please support the usage of a keyfile and password to unlock the bitwarden vault. 

This would increase the encryption strength vastly as it creates a huge password+file combination and would allow to distribute the keyfile offline to separate devices. This would increase at least my sense of security.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
