### ISSUE TITLE
Feature Request: Add support for Authy OneTouch

### ISSUE THREAD

**Issue by justinjstark** [bitwarden/core#190]
Authy OneTouch is similar to Duo Push. It sends a push notification for 2FA.
https://authy.com/blog/authy-onetouch-modern-authentication-for-any-application/

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
