### ISSUE TITLE
Option to Reprompt 2FA When Unlocking

### ISSUE THREAD

**Issue by jou-calvin** [bitwarden/core#192]
I was a user of Password Safe on desktop and Android using a Yubikey Neo. When the database locked on Android, I was required to authenticate with a fingerprint to quickly enter the master password, but I was also required to tap my Neo. There was a Reddit post [describing this issue](https://www.reddit.com/r/Bitwarden/comments/7p5err/yubikey_on_lock/) where an auto log off feature was under consideration. I think that it would be convenient for the user to have the option to enter a PIN/fingerprint and another 2FA method. For me, having to present a hardware token more often in addition to a PIN/fingerprint helps to form a habit to use 2FA, is arguably more convenient than retyping an entire password when logged off, and is more secure than the current setup.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
