### ISSUE TITLE
Send notification to owners when a user accepts the invitation to join an org

### ISSUE THREAD

**Issue by job** [bitwarden/core#204]
When a user is invited to join an organisation, an email is send to the user with a hyperlink were the user can accept the invitation. After the invitation is accepted, the owners of an organisation must confirm the user to admit the user to the organisation.

An email should be send to the owners so they are aware that the user accepted the invitation. An email should be send to the user after the owner confirmed the user. This way some out-of-band chatter can be prevented because the involved parties receive notifications to progress enrolling the user.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
