### ISSUE TITLE
Feature Request: Integrate and Support Mozilla Lockbox.

### ISSUE THREAD

**Issue by bash321** [bitwarden/core#205]
Are their any plans to integrate Bitwarden with[ Mozilla Lockbox](https://github.com/mozilla-lockbox/lockbox-extension)?

**Comment by kspearrin** [comment]
How would we integrate with it? Seems like a competing product?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
