### ISSUE TITLE
Non-scripted on premises deployment

### ISSUE THREAD

**Issue by nmaggioni** [bitwarden/core#211]
It would be nice to have a more rigorous, non pre-scripted way of self-hosting Bitwarden on one's own infrastructure.

I am, for example, already managing a Docker environment via [Rancher](http://rancher.com/) and will soon be migrating to Kubernetes. An externally written script could easily screw something up inside the ecosystem by interacting with the Docker daemon and bypassing the chosen orchestrator.

Something like a plain Docker Compose file or simply a list of required dependencies could greatly help in manually reproducing the automated deployment while keeping it under the chosen orchestrator's management and avoiding conflicts.

**Comment by kspearrin** [comment]
You can see how the compose files are generated here: https://github.com/bitwarden/core/blob/master/util/Setup/DockerComposeBuilder.cs

**Comment by nmaggioni** [comment]
I've noticed that file, but it seems a rather hacky solution to extract a template from it: a large number of relative paths are referenced and env files are imported - plus it's an entirely undocumented approach.

While it could sound like it, this doesn't want to be a critic - I'd be happy to help documenting the process once I'll get to consistently reproduce a scriptless deployment :)

**Comment by kspearrin** [comment]
@nmaggioni That's exactly what it is. I wasn't suggesting that this issues wasn't valid, I'm just trying to point you in the right direction since that's what's available today.

**Comment by cooperaj** [comment]
I'd like to see this for much the same reason. 

Another issue to note is that I'm already running an nginx ingress that will letsencrypt things for me so need to bypass that process. The instructions/process would let me piece together how I might do that.

**Comment by nmaggioni** [comment]
@cooperaj For the moment I solved this by isolating BW inside an LXC container and placing a reverse proxy in front of it.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by mcfedr** [comment]
If your interested, I've been working on a helm chart for running bitwarden, its not quite working yet, but nearly... https://github.com/mcfedr/bitwarden-chart
