### ISSUE TITLE
Support Proxy within the installer and api server?

### ISSUE THREAD

**Issue by jkaberg** [bitwarden/core#213]
You should expose an option to set HTTP(S)_PROXY environment variable within the bitwarden.sh installer script and pass along these values to the setup container. 

eg 

``` 
expose HTTP_PROXY=http://myproxy.local.lan:3128
expose HTTPS_PROXY=http://myproxy.local.lan:3128
./bitwarden.sh install
```
or
``` 
./bitwarden.sh install --proxy http://myproxy.local.lan:3128 --sproxy http://myproxy.local.lan:3128
```

I don't know how the main application handle's this?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
