### ISSUE TITLE
Allow to hide some logins

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/core#217]
Sometimes I want to store passwords that were shared with me but I don't use them on a daily basis, only as a backup when the owner of the account wants me to log in.
Since I also have a personal account (or more) on this service, the different views (contextual menu and extension popup) are cluttered with these accounts I don't need to see.

It would be nice to have a checkbox that would allow me to show/hide this item from the proposed items on a specific website. I don't know how to label it, maybe "disable", or "hide from auto fill". The default case would of course be to display the login in these views.

The items would still be accessible in the vault view or by search, or anywhere else. Just hidden from the propositions that are shown when I try to log into a website on a daily basis.

**Comment by taodailOryx** [comment]
@Crocmagnon Developers have stated that this functionality is planned, see #9. In the mean time, I don't know if this would work for your use case, but for mine, I have a folder named `Other Credentials` that keeps everyone else's details in one place (i.e., away from my stuff).

**Comment by yfdyh000** [comment]
similar: #70.

**Comment by Crocmagnon** [comment]
Is it really ? I'd like to have my logins in the same folder but one of the logins is available for autofill, the other is not.
The related issue is more about organizing items from what I understand 😊

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
