### ISSUE TITLE
Allow for "online-only" folders / selective sync / travel mode

### ISSUE THREAD

**Issue by mariow** [bitwarden/core#218]
Being a current user of 1password I have gotten to like the functionality of removing most of my logins from devices during travel and keeping only the bare minimum of data stored on the devices.

It would be great to see a similar functionality in Bitwarden, ideally allowing me to select which folders should get synced to apps, browser extensions etc. in the web interface. If a folder is de-selected for that sync it should not be visible at all in the app, basically appearing as if it doesn't exist in the first place.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by darkblinded** [comment]
For future readers here is the feature request: https://community.bitwarden.com/t/online-only-folders-selective-sync-travel-mode/345

**Comment by gdudziuk** [comment]
This link doesn't work anymore. Do you know what has been the fate of this feature request? Has it been rejected?

**Comment by mariow** [comment]
@gdudziuk As far as I know the situation still is that no other password manager has a similar feature. Frankly, it's the one thing that is keeping my 1Password subscription alive.

**Comment by tgreer-bw** [comment]
@gdudziuk  @mariow - unfortunately, that thread was cleaned up because it has been inactive since March of 2018.

For travel or minimal vault, for cloud users, you can always create a free 2-person organization and a 'travel' account, sharing only the bare minimum from your 'main' vault.

https://bitwarden.com/help/article/getting-started-organizations/
