### ISSUE TITLE
Invited registrations when registrations are disabled ?

### ISSUE THREAD

**Issue by Mart124** [bitwarden/core#219]
Hi,

When we set `disableUserRegistration=true`, users who have been invited to an organization can't register.
Would then be nice to allow registration of invited users, even if `disableUserRegistration` is enabled.
This would allow to decide who is allowed to register, sending legitimate users an invitation.

Thx 👍

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by mcfedr** [comment]
Apparently this has bug has been fixed in v1.20
