### ISSUE TITLE
Everything runs as root ?

### ISSUE THREAD

**Issue by RuthBo** [bitwarden/core#221]
Hi,

Every bitwarden docker container / service runs as root user.
Even if installed using a non-root / part of the `docker` group user (then facing #186).

Appears to me like a security flaw, if one service get compromized, the whole machine could get impacted.
What about a `bitwarden` dedicated user ?

Many thanks !

**Comment by kspearrin** [comment]
I'm guessing this depends on how you have docker installed and running. We don't specifically run as root in any way.

**Comment by RuthBo** [comment]
According to [this article](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b), I think containers should declare and use a dedicated user, `bitwarden` for example.
If no user is specified, then containers will run as root.

**Comment by chrisls121** [comment]
I noticed my containers running as root as well. I followed the documentation from Bitwarden and the official install documentation for Docker.

I came across that same article too while researching this issue, hopefully those changes can be implemented.

**Comment by kspearrin** [comment]
This is also what is causing #186 , as mentioned earlier. I was able to reproduce it while testing on Ubuntu today.

**Comment by kspearrin** [comment]
I've spent the past few days working on re-factoring our docker images to run as non-root. I now have all container services running under a `bitwarden:bitwarden` non-privileged user. This `bitwarden:bitwarden` user will automatically map it's user id back to your host's user id. This means all mapped volumes will have owner permissions on the host machine set as the host user (`docker:user`). If the host user is root (or running as `sudo`) we still run all containers as `bitwarden:bitwarden`, however, the mapped volumes will be assigned to a default 999 user (`docker:999`). They will never be owned by root since the container's services are not running as root.

`sudo` is no longer required. Existing installations running under `sudo` can `chown -R user:user ./bwdata` to fix permissions on mapped volumes and then abandon `sudo`.

This will be available in the next version.

**Comment by chrisls121** [comment]
Thank you so much, this is awesome, looking forward to the release! :)

**Comment by kspearrin** [comment]
If anyone wants to test this, you can download the regular `./bitwarden.sh` script like normal, then just change the versions for core and beta in there to "beta". You probably shouldn't do this against an existing production installation though.

**Comment by kspearrin** [comment]
Closing since this is now complete for next version.

**Comment by RuthBo** [comment]
Thank you very much @kspearrin, good news for security 👍

**Comment by RuthBo** [comment]
> then just change the versions for core and beta in there to "beta".

for core and api you mean I think :)

**Comment by kspearrin** [comment]
This is now live with version 1.18.0
