### ISSUE TITLE
Enforce master password strength

### ISSUE THREAD

**Issue by Mart124** [bitwarden/core#228]
Hi,

Would be nice to be able to enforce master password strength.
Think about company passwords shared in an organization, and some people using weak master passwords...
Would then be nice to be able to define some rules each master password would have to follow :
- minimal length ;
- character classes ;
- uppercase / lowercase ;
- ...

Thank you 👍

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
