### ISSUE TITLE
Disable registration prevents invites from working

### ISSUE THREAD

**Issue by mcfedr** [bitwarden/core#272]
For self hosted, its preferable to disable registration, but currently this prevents invites from working, meaning you cannot disable registration.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Mart124** [comment]
See #219 & https://community.bitwarden.com/t/allow-invited-people-to-register-even-if-registrations-are-disabled/211

**Comment by mcfedr** [comment]
I guess I didn't see that in search. 

In my mind and I assume for @Mart124 this is a bug not a feature request, but it appears the maintainers feel otherwise.
