### ISSUE TITLE
Emergency Access

### ISSUE THREAD

**Issue by sreich** [bitwarden/core#28]
Lastpass has a feature that's basically for emergencies, where you can set a timeout and a user to be granted access. 

The user then at any time can request access, the owner gets an email. If they don't click reject in the email it opens up access after that time period. Like 48 hours for instance. This is for example useful if you get in a medical accident or die.

It would also be nice to restrict which sites they get access to (all or "selected").

https://helpdesk.lastpass.com/emergency-access/

**Comment by kspearrin** [comment]
We can easily add this once we get the share architecture with public key exchange in place. Dependency on https://github.com/bitwarden/core/issues/26.

**Comment by shogsbro** [comment]
I suggest granting user is able to adjust the timeout, or replace it with a date, in case he/she goes moonwalking without access to email.

Alternatively, make it a delta from last login/use of Bitwarden?

**Comment by lyndsysimon** [comment]
I'm interested in this for continuity purposes in the event of my death. I've got several important credentials stored in bitwarden that would make my estate's executrix's life much easier.

From this perspective, I'd like to be able to designate a series of individuals to try. My ideal would be something like this:

1. I set up a list of email addresses in order of precedence: my wife, my mother, my attorney
1. My account goes inactive for 30 days
1. I get an email warning me that my account will be made available to my emergency list in 14 days
1. If I ignore that email and the (several!) that follow, then my wife gets an email prompting her to create a bitwarden account which will have access to my credentials (or a subset thereof).
1. If my wife does not create that account within seven days, my mother gets an email.
1. If my mother does not create that account within seven days, my attorney gets an email.

**Comment by jimmystridh** [comment]
@kspearrin with vault sharing in place, is this feature on the roadmap?

Trying to decide if it's worth sticking with L.P. for another year or if I could do without this feature and put my master password in an envelope somwhere.

**Comment by kspearrin** [comment]
@jimmystridh It is still planned, not not prioritized at this time. My guess would be sometime in first half of 2018.

**Comment by sNiXx** [comment]
+1 for this feature.
It would finally allow me to move away from LP. Thanks for all the great work either way!

**Comment by nat45928** [comment]
Agreed, this is the last thing keeping me from moving from last pass full time.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/emergency-access/115

This issue will now be closed. Thanks!
