### ISSUE TITLE
[new feature] stateless password generation

### ISSUE THREAD

**Issue by fallerOfFalls** [bitwarden/core#30]
The other password system I love, is [Master Password](http://masterpasswordapp.com/). A stateless password system is definitely my favourite (I enjoy the absolute confidence that I can NEVER lose my passwords). Unfortunately there are always going to be passwords that cannot be changed, and that need to be remembered, so a stateless system can only really work as part of a more traditional password manager like bitwarden. I would *love* bitwarden forever/so much if it had the option to generate passwords in this stateless way (using Master Password algorithm).

Probably not something you'd want to even look at implementing at this stage, but someday, maybe?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
