### ISSUE TITLE
Add icons for site logins

### ISSUE THREAD

**Issue by sreich** [bitwarden/core#32]
Websites in both web and mobile should utilize the sites icon in the listing (and edit pages). Just like LastPass has.

**Comment by kspearrin** [comment]
Likely won't happen any time in the near future, but I'll leave it open.

**Comment by jawz101** [comment]
While favicons are pretty some browsers are ditching support for them as users might associate them with a sites validity.  Also, since many sites don't even offer favicons, the consistency would have many going "Aww... most of my sites don't have pretty favicons."

http://www.wired.co.uk/article/firefox-fires-favicon

Just my opinion.

I could see it being nice to have some sort of icon to acknowledge site security for each of your saved credentials.  For instance, each time a login is used it checks for forms with an expired certificate or un-encrypted and your vault flags them as pink or something.

**Comment by jarbro** [comment]
I second some sort of graphic representation of the site your going to, whether it be pulled from a sites favicon or some other popular sites db.  The article @jawz101 referenced was from 2012, and the favicon has not been killed off entirely.  Maybe in the address field, but it is still alive and well for bookmarks.  In fact the bitwarden site has one, as does github. 
![firefox_2017-05-09_15-32-34](https://cloud.githubusercontent.com/assets/3271673/25869049/eb7696e0-34cc-11e7-87b6-d1b13fbfdd41.png)

Many other password managers give you the option to use a graphical representation of the entry including Lastpass, 1password, Dashlane. Would be nice if bitwarden did as well.

**Comment by jawz101** [comment]
@jarbro you shouldn't dismiss something because it's from 2012 when it comes to privacy and security.  Like, I would think I would've forgotten something so obscure by now :)

Maybe certain techniques theorized a few years ago might actually be used today.  The modern web and browsers have added all sorts of arguably useless variables -virtual reality enabled web pages, device sensor access, camera face detection, gamepad access, ability to read battery level... all stuff currently in my browser yet never used by me... or anyone, really.  I just wouldn't dismiss an old story without consideration.

**Comment by jarbro** [comment]
@jawz101 I hear your porn example, however I think that is the exception rather than the rule.  In most corporate environments users are not allowed to install applications on their workstations.  I understand the case for the local client, but in a web browser/mobile client, grabbing the site icon once and storing it seems like a logical solution. No web requests would have to go out to grab the icon since it's already stored.  At the end of the day, having the site icon makes it much easier to quickly find the site entry you're looking for.

**Comment by Hinton** [comment]
Looking at how other password managers solve the issue, both [LastPass](https://lastpass.com/support.php?cmd=showfaq&id=10022) and [1Password](https://support.1password.com/privacy-rich-icons/) seems to use a centralized database of icons. Furthermore it they both decided to avoid using favicons and instead opted for larger high-res images, which they [manually manage](https://discussions.agilebits.com/discussion/75862/rich-icon-submissions).

I think the most realistic solution would be for bitwarden to run it's own database which primarily acts as a "proxy" / "cache" to favicons but also support high-res images for popular websites. It would also be possible to rely on Google to provide the favicons, using the Google S2 Converter (https://www.google.com/s2/favicons?domain=google.com).

A disadvantage to this solution, is that it "leaks" the domains to either bitwarden or Google. On the plus side, it would not be possible to monitor the network traffic for requests to objectionable websites.

Another alternative is for the browser extension to store and update the favicons only when the website is visited, which would result in no additional traffic. This has the disadvantage of only being able to use the favicons and not higher-resolution icons, slower update rate since the website has to be visited, and involves additional storage.

**Comment by kspearrin** [comment]
done for next release
