### ISSUE TITLE
Add history to all fields

### ISSUE THREAD

**Issue by sreich** [bitwarden/core#33]
Lastpass stores the previous passwords when one is changed. This is great especially if you accidentally overwrite the previous one or realize you need it.

This is most important for secure notes and the notes section of logins as it's possible for you to accidentally mess them up. This is important because usually they have security questions stored in them.

So an ability to see previous versions of them would be a very good feature.

**Comment by evazquez00** [comment]
Especially if (and this never happens, right?) Firefox /Chrome /$BROWSER crash halfway through updating /changing a password.

**Comment by bj0** [comment]
I would like to see a "password archive", where all replaced, deleted passwords get stored.  This would solve all these problems.  It would also let you search for old/deleted passwords if you find you need one again for some reason, or you just need to audit your password history.

**Comment by rggjan** [comment]
I think the password archive idea that keeps all the old password in one place could get a bit messy and hard to search in. I like the LastPass approach: Keeping an archive of completely deleted password entries, and additionally have a history for each field (like password, user name, notes) for both active and deleted entries.

**Comment by viertaxa** [comment]
I missed this issue when looking earlier, but here's my extremely rough mock up of what it could look like for the password history: **https://imgur.com/a/HXiY0**

**Comment by rggjan** [comment]
Looks great! Now this is just missing for all the other fields in the mockup...

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/vault-item-modification-history/179

This issue will now be closed. Thanks!

**Comment by ajayyy** [comment]
Was this not done to secure notes like in the original feature request?
