### ISSUE TITLE
[Suggestion] Add options to re-prompt for master password

### ISSUE THREAD

**Issue by yureiita** [bitwarden/core#35]
Re-prompt for your bitwarden master password before you:

    Access an Identity
    Access a Site's password
    Access a Site
    Access a Secure Note
    Access a Form Fill
    Log into a site

E.g. taken from LastPass

**Comment by jungle-boogie** [comment]
An obvious item to be implemented.

**Comment by kriswilk** [comment]
I view this as a very high-priority issue. In addition to the above-mentioned global settings, I think there should also be a granular login/identity/card option like:

- Reprompt for password/pin/fingerprint to access this record

For instance, I'd enable this for sites with TOTP generation to mitigate the security risk of storing the TOTP secret with the site password. When I log into such a site, I'd feel safer if bitwarden required my password/pin/fingerprint before filling the login and copying the TOTP code to the clipboard.

I have plenty of other "sensitive" logins that I'd prefer to hide behind an extra prompt in the same way.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/require-master-password-re-prompt-for-some-items/41

This issue will now be closed. Thanks!
