### ISSUE TITLE
Import of bitwarden style .csv ignores existing collections

### ISSUE THREAD

**Issue by Zoba273** [bitwarden/core#377]
Hi,

when you import files via .csv file, it creates a new collection instead of adding the entries to existing collections.
I have a pre-existing collection and wanted to add a bunch of logins to that collection via csv. Instead of my expected behaviour bitwarden ignores the existing collections and just adds another collection with the same name. Is that intended? Is there a way to add multiple logins to existing collections?

**Comment by Zoba273** [comment]
Affirmative. Then you can go ahead and close this issue.

**Comment by Jack0r** [comment]
4 Years later and this still seems to be the case. So we are supposed to purge our whole database if we have to import stuff into existing collections? We are currently trying to migrate to bitwarden from several older systems and this is just plain bad design. I accidently removed wrong collections because they all had the same name. 

Do you still think this is good design? Importing should be a simple task but this makes it a horrible experience. As it looks right now, we will have to move our whole company to another solution. I cannot import several thousands passwords by always having to kill the whole database of the company just to import into an existing collection.

Allowing the system to create a second collection with the EXACT same name, which makes it indistinguishable for any human is just bad design. Of course, in the background it will have some ID so the system can distinguish it, but maybe I want too?
