### ISSUE TITLE
Enforce master password strength

### ISSUE THREAD

**Issue by Mart124** [bitwarden/core#402]
Hi @kspearrin,

I've seen you've just implemented master password strength verification in web vault, advising user to choose a stronger password if needed. Nice !

Would be nice to give the server admin the ability to enforce master password strength so that user **can't** use a weak password.
Technically, selecting character classes (lowercase, uppercase, numbers, special characters...) to enforce, and a minimal length ? Or simply a regex in the server configuration file...

Then, you could add such generated rule as a `pattern` option to the HTML form field, for example :
`pattern="(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[^0-9a-zA-Z])[^\0]{16,}"`
Which is : numbers, lowercases, uppercases and special characters required, with a min length of 16.

Of course this does not prevent a "malicious" user to bypass the constraint (but why would he do this ?!), but as verification can't be done on server side, I see no other way.

Many thanks 👍

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
