### ISSUE TITLE
Add support for storing software license details

### ISSUE THREAD

**Issue by cweagans** [bitwarden/core#404]
1password has this. I can sort of make due with secure notes, but it would be really nice to be able to break out my software licenses into a separate type in the sidebar.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
