### ISSUE TITLE
Allow logins from only certain countries

### ISSUE THREAD

**Issue by jawz101** [bitwarden/core#41]
I really like Lastpass' feature to restrict logins to only certain countries on an allowed list.

I see MaxMind free location tables https://www.maxmind.com used a lot for this though I'm sure there are probably others out there.

The only time I allow any other country might be if I'm on vacation and I definitely block all TOR login access.

**Comment by cwmke** [comment]
I agree although I would make blocking Tor access an opt-out option so that Tor users aren't prevented from using bitwarden.

**Comment by mikecrittenden** [comment]
Just want to pitch in and say this is really the only thing I'm missing from Lastpass that bothers me. It's a nice safety net to know that even if somehow my master password was exposed, it would still be useless unless the person lived in my country (or possibly was using a VPN showing that they were in my country I suppose).

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/restrict-account-access-to-certain-countries-ip-ranges/180

This issue will now be closed. Thanks!

**Comment by TomLewis** [comment]
> Oops! That page doesn’t exist or is private.

Was this ever implemented? Requested in 2017 and its now 2022.
