### ISSUE TITLE
trusted devices

### ISSUE THREAD

**Issue by nilsbecker** [bitwarden/core#42]
anyone who has the username/password combination gets full control over a vault. it's a little disconcerting that anyone from anywhere can start trying brute force attacks.

would it help security if 

1. any first login from a new device would trigger an automatic email? 

2. or better, designate a 'trust center' device or secret key file which is necessary for adding access from any new device in addition to the master password.
that way, logins from trusted devices (identified by a stored secret key) would still be fast but the attack surface would be reduced. 
what happens if the trusted key or device is lost? then login with only the master password must still be possible but could be protected with a long waiting time (hours/day?)

3. maybe simpler, a mandatory long waiting time for first login of each new device.

(sorry if this is naive, not a security expert. 
but  i remember lastpass having at least email notification)

**Comment by kspearrin** [comment]
This is essentially what two-factor authentication is for. Right now, 2FA is opt-in since we only support authenticator apps and that requires set up.

This problem could be solved once we add an email-based 2FA (https://github.com/bitwarden/core/issues/5). Email is obviously less secure than the authenticator app option, but we could possibly enable it by default for all new accounts so at least there is some other factor involved initially.

**Comment by kspearrin** [comment]
Additionally, we have other brute force measures in place for authentication that reduce the threat like degrading sleeps on failed login attempts.

**Comment by nilsbecker** [comment]
ok. i find two-factor authentication e.g. with a cell phone on each and every log-in a bit of a burden, so i personally would like to avoid using it.

**Comment by kspearrin** [comment]
@nilsbecker I have plans in a coming release to make it so that you only have to do it once per device.

**Comment by nilsbecker** [comment]
cool!

**Comment by kspearrin** [comment]
This is one for next release. You can remember a second factor auth for 30 days.
