### ISSUE TITLE
Auto folders when collection shared

### ISSUE THREAD

**Issue by iain-id** [bitwarden/core#45]
When a new collection is shared with a user it would be helpful to have an option as the user or the admin to automatically have the collection added as a folder.

I am looking at this as a new company about to use the product.  I am likely to create a number of collections to be shared with the staff.  The collections will already be in the groups the users would likely want the passwords managed as folders.  As I can see most users when they are first shared their list of passwords to never move the logins into folders as its too much work when faced with a list of 100+ new logins.

**Comment by kspearrin** [comment]
Thanks for the feedback.

**Comment by kspearrin** [comment]
The problem here is that folders are user specific and are not in the realm of sharing. Folders are encrypted with the user's encryption key, not the organization's (like collections). Because of this, no other user (like the org admin) can add or edit a user's folders.  

Two ideas:

One approach here is to add a button for a user to click from their vault that will allow them to "Create folders from collections" that will setup a folder structure that matches the current collections. Of course this would only be a one time thing and newly added logins to those collections wouldn't automatically follow. A user could periodically click the button to re-organize them though.

Another alternative is to allow the client applications to just browse the vault based on the organization, where things are organized by collection rather than folders. This is already done in the web vault (Shared page).

**Comment by jaybinks** [comment]
I am also evaluating bitwarden with the view of rolling out the premium version to our company.
This has already been flagged as a usability issue, that may detract from us settling on bitwarden.

Even if the collection name were to show up as the folder ?

**Comment by kspearrin** [comment]
This is no longer necessary since we sync all collections and their structure down to user devices.

**Comment by Mart124** [comment]
@kspearrin, do you mean that, now, folders from collections are synced when a collection is share with new users ?
Are they kept in sync, for example if a new folder is added to a collection and some passwords are added into this folder, will this structure be properly synced with all the users sharing this collection ?
Or do the user "still" receive the new passwords in a "No folder" folder ?
Many thanks !

**Comment by Mart124** [comment]
> we sync all collections and their **structure** down to user devices

I'm not really sure what you mean by structure.
Do you mean @kspearrin that, now, folders from collections are synced when a collection is share with new users ?
Are they kept in sync, for example if a new folder is added to a collection and some passwords are added into this folder, will this structure be properly synced with all the users sharing this collection ?
Or do the user "still" receive the new passwords in a "No folder" folder ?
Many thanks !
