### ISSUE TITLE
Updates via API, or just general documentation

### ISSUE THREAD

**Issue by evaryont** [bitwarden/core#46]
It would be nice to explain what API that does exist, and how to interact with the encrypted blob that is the user's vault.

My end-goal: Create a cron job with [pass-rotate](https://github.com/SirCmpwn/pass-rotate) that will change my passwords and update the vault, all automatically. Basically, I want to update my Github/Twitter/Facebook passwords more often, but it'd be nice to have my computer do that for me.

**Comment by RomanHargrave** [comment]
This is definitely something I would like, as I would like to be able to self-host, and while BitWarden provides frontend that I can easily use, the technology stack used for Bitwarden Core is not one that I am partial to, as well as completely different from the preexisting infrastructure I have, which would require extra resources and time.

If there were detailed documentation (even an implementation guide!) for BW Core, it would simplify the process of writing an alternative backend that uses more conventional technologies for non-Windows hosting.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
