### ISSUE TITLE
Bulk Share Passwords

### ISSUE THREAD

**Issue by PyroclasticMayhem** [bitwarden/core#49]
I've been trying to share many passwords with a collection. I noticed that the only area that allows doing it is the gear icon next to the password.

**Comment by pauldalewilliams** [comment]
I'll second this.  It was my first major annoyance when testing this for my team at work.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/bulk-share-items/181

This issue will now be closed. Thanks!
