### ISSUE TITLE
Audit History

### ISSUE THREAD

**Issue by jarbro** [bitwarden/core#51]
Currently a paid customer and would love to see an audit trail for all entries.  Would love to know who changed passwords, when, from > to, etc.

**Comment by jeroen7s** [comment]
agree, there should definitely be a comprehensive history for entries that changed, as well as trash bin functionality for entries that have been deleted by someone (including that history)

**Comment by wotanvonklass** [comment]
We would need the information which user used which password. Is such information available in any log files?
This would be a workaround for us.

**Comment by kspearrin** [comment]
There are no log files for this at this time.

Thinking about this more, what constitutes that a user **used** a password? That they viewed it? Copied it? Auto-filled it?

**Comment by wotanvonklass** [comment]
I mean "accessed" it. This should include all possible sub-cases (exported, copied, viewed, filled). Having this in logs, would allow me to have less passwords to change when a colleague leaves the company. 
It would be even better to have UI-reports like "Passwords used by user x since y" or show all usages of a selected PW.
BTW, we are also a paying customer. Having such "enterprise" features, would enable us to roll Bitwarden out to all employees.

**Comment by kspearrin** [comment]
This is planned (as noted on the product website) for enterprise plans, though there is no timeline at this time.

**Comment by kspearrin** [comment]
Event logs are now available for enterprise organizations.

**Comment by jeroen7s** [comment]
any updates for password/entry history for personal use?
