### ISSUE TITLE
Support equivalent domain rules for local domains

### ISSUE THREAD

**Issue by 13xforever** [bitwarden/core#53]
I.e., if I have local domain `.asdf` and global domain `.asdf.com`, then I can't just use the rule `asdf.com, .asdf`, which is not very convenient.

Note that you can't use 'asdf' as this will refer to the host names on the lan.

(`*.domain` also doesn't work)

**Comment by evazquez00** [comment]
As a contractor that works for /with companies that have multiple subsidiaries, this would be very helpful indeed!

**Comment by miguelfc** [comment]
+1

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
