### ISSUE TITLE
[Suggestion] Invitation links should activate the bitwarden app.

### ISSUE THREAD

**Issue by dabura667** [bitwarden/core#56]
Slack's UI is great for links.

1. Click the magic link.
2. The landing page has a button for people with the Slack app (if the user agent is mobile) and clicking the button will link to a slack:// link which is registered as the URI scheme for slack's app, opening the app.
3. The app grabs the necessary information from the slack:// link and performs the action.

A similar process could be used for organization invites etc.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
