### ISSUE TITLE
[Suggestion] Allow altering the number of hashing iterations

### ISSUE THREAD

**Issue by mbirth** [bitwarden/core#57]
LastPass allows one to change the number of hashing iterations for the credentials. Default seems to be a value of 5000, but due to more and more capable hardware, a value of 50000 or more doesn't impact the performance much, but makes it far more difficult to brute force the master password.

See also: https://helpdesk.lastpass.com/account-settings/general/password-iterations-pbkdf2/

**Comment by kspearrin** [comment]
Also discussed here https://github.com/bitwarden/browser/issues/31

**Comment by petervnv** [comment]
I think that's a must have nowadays considering the threat level is so high.
What implementation of PBKDF2 is bitwarden using (SHA-1 or SHA256)?

Also, where can I find this in the code?

Cheers,
Peter

**Comment by kspearrin** [comment]
PBKDF2 SHA-256

**Comment by petervnv** [comment]
Excellent! Thanks

**Comment by jungle-boogie** [comment]
Even though I use an older laptop, I wouldn't mind waiting an extra 30 seconds for my vault to be unlocked, because of the iterations being performed.

**Comment by msrv** [comment]
@kspearrin i think this is one of the most important things in bitwarden. I host bitwarden myself and purchased a premium membership today to support your excellent work, so thank you for your efforts! I have been a long time keepass user but got sick of the dated ui and sync + extension problems...

The numer of iterations matter the most if someone uses bitwarden in the default, Microsoft Azure Cloud environment. 5000 Iterations of PKDBF2-SHA265 are nothing to the overwhelmingly powerful Microsoft Cloud. Just imagine (paranoid mode ;)), their automated scanning found a bitwarden account (as the email adress etc. is not encrypted) of "mrsupervillain" and put their complete computing power in cracking the bitwarden database...i don't think that 5000 iterations even with pkdbf2 would stop them.

If you could chose an unlimited amount of iterations (like in keepass for example), it would give a greater sense of security...so please, implement an option to customize the iteration count :)

**Comment by kspearrin** [comment]
@msrv Just so you are aware, the password at rest (stored in the database) is iterated over 10k more times by the server before storage (totally 15,001 iterations). 5k is just what happens when the API calls the server in transit. I'm not saying that's much better in the situation you have described, but thought I should clarify.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/user-configurable-key-derivation-iterations-key-stretching/16

This issue will now be closed. Thanks!
