### ISSUE TITLE
Bitwarden to act as a SAML SP for SSO onboarding

### ISSUE THREAD

**Issue by stev-it** [bitwarden/core#63]
hey,

I just wanted to ask if its planned to add an SAML or SSO called Feature into bitwarden.

**Comment by kspearrin** [comment]
Have not considered it. How would it work?

**Comment by stev-it** [comment]
Like the "Single Sign On SAML" to Azure Active Directory.
https://docs.microsoft.com/en-us/azure/active-directory/active-directory-appssoaccess-whatis

**Comment by kspearrin** [comment]
Yes, but I don't see how SSO is possible with bitwarden since the application needs a user's encryption key, which involves typing a master password into bitwarden itself. If authentication happens on some other system, how would that be possible?

**Comment by stev-it** [comment]
Okay, thank you for your kind and fast response. I guess i just thought on a wrong path on this and thought this was possible, but indeed, it is not practically possible.

**Comment by kubrickfr** [comment]
@kspearrin, I'm migrating from LastPass to bitwarden (and I'm already a paying customer).
LastPass can do it, so I'm sure bitwarden can too.
To answer your "question" this is exactly what happens with LastPass: when a third party requires authentication, LastPass prompts for the master password. I have been using it with google G suite for a couple of years, it does the user provisionning and everything, works very well.

**Comment by kspearrin** [comment]
@kubrickfr that’s because lastpass acts as the IDP. I think what was originally suggested in this issue was bitwarden acting as an SP.

**Comment by kubrickfr** [comment]
@kspearrin I don't know what @stev-it meant. But I'm definitely talking about bitwarden acting as an IDP. Should I open a seperate issue? Rename this one?

**Comment by kspearrin** [comment]
Feel free to open a new one. I will re-open this one to explore bitwarden as a SP.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/act-as-a-saml-service-provider-for-onboarding/183

This issue will now be closed. Thanks!
