### ISSUE TITLE
Auto Logoff

### ISSUE THREAD

**Issue by amentmcloughlin** [bitwarden/core#64]
Now that TOTP has been implemented this has the effect of allowing a single 2FA (giving access to Bitwarden) to give access to multiple applications that require 2FA. It then becomes essential that one logs off Bitwarden rather than just locks it. Otherwise, one is compromising 2FA on other applications.  Can we have an Autologoff facility similar to the Autolock.

**Comment by kspearrin** [comment]
This is planned.

**Comment by jungle-boogie** [comment]
It seems I opened a similar issue here: https://github.com/bitwarden/core/issues/146

I wouldn't like to see this implemented only for 2FA, though. It should be an option (and enabled) across all accounts, IMO.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/auto-logout-after-x-minutes/30

This issue will now be closed. Thanks!
