### ISSUE TITLE
Multiple U2F key support

### ISSUE THREAD

**Issue by kri5** [bitwarden/core#65]
A typical U2F user workflow is to have at least two keys, one for daily use, another as backup.
As of now it seems that we can only register one U2F key at a time.

It might be very useful to be able to register/manage/unregister multiple keys.

Many website supporting U2F provides this (google, facebook, github, gitlab,... )

**Comment by kspearrin** [comment]
This is planned.

**Comment by eldridgea** [comment]
In building the feature, can we have the ability to custom name keys? e.g. "keychain" and "backup"?

**Comment by nbebout** [comment]
This would be very nice to have.

**Comment by kriswilk** [comment]
Looking forward to this...

With multiple U2F key support, I could plug (and leave inserted) keys into every one of my PCs for a good balance of security and convenience. For example, Yubikey Nano...although since I'm not made of money, I'd probably go for a cheap alternative like [HyperFIDO](https://www.amazon.com/HyperFIDO-Mini-U2F-Security-Key/dp/B01LZO0WE9) or the even smaller, open-source [Tomu](https://www.crowdsupply.com/sutajio-kosagi/tomu) in U2F mode:

**I strongly suggest not putting an artificial limit on the # of keys**. Many services limit to 3 or 5 but I could easily use up to 10 just between home and work...

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/support-multiple-u2f-keys/117

This issue will now be closed. Thanks!
