### ISSUE TITLE
Display the date of the last password change

### ISSUE THREAD

**Issue by etix** [bitwarden/core#66]
As discussed on Gitter, a nice and quite simple feature would be to display the date of the last password change. This can be useful to:
- know when it's time to renew your password according to your own policy
- know if your password was involved in a data breach or not

This feature will probably be interesting for #33 as well.

**Comment by jungle-boogie** [comment]
I support this change. I don't know if LP had/has this feature. I'd usually type in a note when the account was created and when the passwords were updated. If this would be implemented, it would be nice to see all the history: created, changed, updated, etc. Not just the most recent change.

**Comment by rggjan** [comment]
The advantage to the workaround with entering it in the notes would especially be sorting/filtering (eg "show all passwords sorted by longest time not changed" or "show all passwords not changed for more than 5 years")

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/password-expiration-date/162

This issue will now be closed. Thanks!

**Comment by jpbaril** [comment]
The newly created topic [162](https://community.bitwarden.com/t/password-expiration-date/162) is not related to this issue.

**Comment by kspearrin** [comment]
Also similar https://community.bitwarden.com/t/vault-items-last-revision-date/148

Please re-open the request on the forums if these do not satisfy the requirements of the original request here.

**Comment by jungle-boogie** [comment]
> We are moving away from tracking Bitwarden feature requests like this one as GitHub issues.

Where will bugs be tracked?

**Comment by kspearrin** [comment]
@jungle-boogie Still in GitHub
