### ISSUE TITLE
Multiple accounts/databases

### ISSUE THREAD

**Issue by bithost** [bitwarden/core#70]
Hello, 
  I am now using KeePass and have two databases opened: Work and Personal. Is there a  way to have same thing with BitWarden? Our company is planning to test it and would like two have my personal and work. 

Thanks, 
  Tadas

**Comment by kspearrin** [comment]
This is not possible currently, though you could do something of similar effect by using folders to organize data. You would need two different accounts if you want them to be split out entirely.

**Comment by 0b10011** [comment]
[LastPass also has a feature like this](https://enterprise.lastpass.com/getting-started/link-personal-account/). Allows for the two accounts to remain separate, but gives the user access while logged in to their business account. The admin, however, only has access to the entries in the business account.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
