### ISSUE TITLE
Verification Code - Icon or Visual Que

### ISSUE THREAD

**Issue by aaronstuder** [bitwarden/core#75]
It would be nice to have a icon or visual que that represents if the login contains a verification code setup so you can quickly identity if a login has a verification code setup

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
