### ISSUE TITLE
Bitwarden to act as a SAML IDP for SSO authentication & user provisionning

### ISSUE THREAD

**Issue by kubrickfr** [bitwarden/core#80]
Like LastPass, allow integration with SAML compatible services, such as Google G Suite, to authenticate users and do automatic provisioning.

**Comment by kritop** [comment]
is this being considered at all? This would greatly enhance the Enterprise use case.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/act-as-a-saml-identity-provider/187

This issue will now be closed. Thanks!
