### ISSUE TITLE
Support for password grid as MFA

### ISSUE THREAD

**Issue by kubrickfr** [bitwarden/core#81]
See https://helpdesk.lastpass.com/multifactor-authentication-options/grid-multifactor-authentication/ for an example.

It's great to have a MFA not based on an electronic gadget, one that can be carried in a walled and backed up in a physical vault at the same time.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
