### ISSUE TITLE
Prompt Password When Viewing/Using a Specific Login

### ISSUE THREAD

**Issue by hacker1024** [bitwarden/core#83]
It's the one thing keeping me with LastPass. On Android, you should be able to authenticate with your fingerprint, too.

**Comment by davidkassa** [comment]
#119

**Comment by jw-00000** [comment]
+1. I'd especially like to use this for credit card numbers.

**Comment by edsimpsons83** [comment]
+1 Really the only missing feature from LastPass I use.

**Comment by hrach** [comment]
Wanna just point out that this is quite important security feature and should be as such considered :)

**Comment by johnwittacre** [comment]
+1. Don't trust storing some information in BitWarden without a password reprompt feature.

**Comment by haveneersrobin** [comment]
+1. Shame that this is not implemented yet

**Comment by arth33** [comment]
I agree with this. It's a vital feature, selective security. I don't want to necessarily open up everything all the time.

**Comment by DarkArc** [comment]
:+1: This is something important, that's definitely still missing

**Comment by Metal0gic** [comment]
agree with all above.
very important.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/require-master-password-re-prompt-for-some-items/41

This issue will now be closed. Thanks!
