### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by Techwolf12** [bitwarden/core#9]
Something I really miss in bitwarden is that I can't have a folder in a folder. 
Maybe an idea to implement?

**Comment by kspearrin** [comment]
I am not sure I really see a need for this level of organization and complexity in the system. I'm curious to see if others agree.

**Comment by KarimGeiger** [comment]
I kind of (dis)agree with both of you. I don't think multiple levels are needed, however I think there should be a distinction between passwords and secure notes, like LastPass has. They too don't support sub-folders (I think), but they allow you to differ between these two types which is pretty handy.

**Comment by Techwolf12** [comment]
An example folder structure might be:
- Personal
   - Sites
   - Email
- Work
   - Servers
   - Sites
   - Email
- Clients 
   - Client 1
   - Client 2


This functionality can be added in front-end only by for example using Personal|Sites or another character in between.

**Comment by JuHwon** [comment]
+1 
I really would need this features. Its kind of a deal breaker for me right know. since id like to structure my passwords like described above.

* Company A
   * Databases
   * Servers
   * Sites
* Company B
   * Databases
   * Servers
   * Sites
* Project X
   * Databases
   * Servers
   * Sites
* Personal
  * ...

If i cant group  passwords like that it is all messed up.

Im also thinking of an other approach though. **What about labels?**
Labels offer the possibility to structure as complex as the user wants though its not a complex ui or anything like that. Just label all ur passwords with a view labels u want and then search for them.

**Comment by kspearrin** [comment]
Would naming your folders like this not be acceptable?

- Company A > Databases
- Company A > Servers
- Company A > Sites
- Company B > Databases
- Company B > Servers
- Company B > Sites
- Project X > Databases
- Project X > Servers
- Project X > Sites
- Personal > ...

Searchable lables/tags would be much easier to support than a hierarchical folder structure, but that is still a "flat" organization system.

**Comment by JuHwon** [comment]
Naming folder like that sounds like a workaround which is not very convenient to me.
I would actually prefer label/tags over multi level folder structure. 

When one can tag an entry with the tags e.g. `Project X` and `Database`. Then one can search for multiple tags e.g. `Project X` and `Database`. This sounds like a very good solution to me and should cover every structural requirement i guess since tags are much more flexible.

**Comment by Techwolf12** [comment]
I found out something called [EnPass](https://enpass.io), unfortunately closed source. It does save password, has a folder structure like this, can generate OTP and syncs over your own systems (like ownCloud).

**Comment by kspearrin** [comment]
I'll plan to support multi-level folders and tagging in the future.

**Comment by sethlyons** [comment]
+1 for tags!

**Comment by Lavenblade** [comment]
At first I was really wanting sub-folders to be a thing too, but I think tags would be great as well. In fact, tags would essentially offer more functionality like @JuHwon mentioned.

Being able to filter search results even further based on multiple tags sounds awesome.

**Comment by ClarkeCC** [comment]
+1 for folders, sub folders, and tags!

**Comment by evazquez00** [comment]
Weighing in - definitely need Sub-Folders, and tags/labels would just be icing on the cake!

**Comment by maxhq** [comment]
Subfolders are essential for power users that have more than a few dozen passwords to organize.
I also use Keepass and have structures like Devices/ServerA/App1/RootUser etc.

Also at least the iOS app makes selecting passwords by folder almost impossible as all folders are currently uncollapsed and you have to scroll through a huge list. IMHO tapping folders is the preferred navigational method in contrast to typing (search) on a smartphone.

**Comment by jaybinks** [comment]
I am evaluating bitwarden with the view of rolling out the premium version to our company.
This has already been flagged as an issue for one of our teams, that may detract from us settling on bitwarden.

We need something like : 

"IT Services"
    "Client A"
        "AD Admin password"
        "Security system password"
        "Blah"
           "Roll A"
           "Roll B"

   "Client B"
        "Root server password"
        "system password"
        "Blah"

"Network Operations"
   "Datacentre A"
        "System 1"
           "Roll A"
           "Roll B"
        "System 2"
        "Blah"

   "Datacentre B"
        "System 1"
        "System 2"
        "Blah"

"Accounts Team"
   "Billing System"
        "System 1"
   "Finance System"
        "System 1"

**Comment by JuHwon** [comment]
What about this tagging feature? Is this still planned?
Its imo rly a mandatory feature.

**Comment by Maikinoki** [comment]
+1
Subfolders would be a great improvement!

**Comment by qmex-mp** [comment]
Its the same here, we are evaluating this for our Company as Enterprise Account, we have more than 1400 Passwords for our Systems and Client Systems so it would be very important to create subfolders.

**Comment by kspearrin** [comment]
Not sure if you all have noticed, but we've slowly been adjusting the layouts in our apps so that things like subfolders will be possible in the future.

**Comment by sethlyons** [comment]
adding my two cents, i strongly prefer tags over sub-folders.  i think of it in terms of a gmail model -- no need to put mail in folders, just give it a tag (or multiple tags) and then search for the tag(s) as needed.

**Comment by chrisls121** [comment]
Excellent, looking forward to the release of the sub-folders functionality!

**Comment by taodailOryx** [comment]
I'd like to add a vote for tags (but I think tags and folders are complementary, and would love to have both).

Example use case: I migrated hundreds of items manually from Safe in Cloud to bitwarden. Many of these cards have 2-step verification via SMS (this is just an example, there are many other use cases for tags).

With tags, it's easy to add a tag to every card that uses a particular phone number for SMS verification. Am I getting a new phone number? Fine, I'll search for that tag, which pulls up every login that needs to be updated. Now, I can log into each site in turn, update my credentials with my new number, and then remove the old tag and attach a new tag with the new number. At every step, I know exactly how many updates need to be done and how many have been done.

With bitwarden, this is currently not possible. bitwarden doesn't index items beyond the name and the login value as far as I can tell, so there's no way to use a custom field, and obviously I can't have a folder named a particular phone number and put items in it (although subfolders would be a very clunky workaround if that's what it comes to).

Sorry for the wall of text and thanks for all your work. I'm a huge fan of the project and glad to be off of Safe in Cloud, although I do miss my damn tags 😂

**Comment by Julime** [comment]
This Feature would be essential for us to use bitwarden

**Comment by fone** [comment]
I'm currently doing a trial, considering moving over from sysPass. the one thing I'm really missing is tags. the sub folders would be nice, but tags would be a lot more useful to me personally.

**Comment by tomskovich** [comment]
We're also looking for a new password manager, and thusfar BitWarden is great.
However, we also require subfolders in order for us to migrate. Just thought I'd leave a comment to show my support.

**Comment by Morgy93** [comment]
subfolders +1

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/sub-folders-to-organize-vault/137

This issue will now be closed. Thanks!

**Comment by kspearrin** [comment]
Tagging tracked here: https://community.bitwarden.com/t/tagging-items-in-vault/132

**Comment by kspearrin** [comment]
For anyone that was following this issue, sub folders are now possible as a beta test in the web vault. See update here: https://community.bitwarden.com/t/sub-folders-nested-folders-to-organize-vault/137/31?u=kspearrin

**Comment by deathwishdave** [comment]
Tags please. Much more versatile than folders.

**Comment by KrisPetkov** [comment]
I'm also voting for tags. In my opinion they are the best solution and much flexible to use

**Comment by SaberRiryi** [comment]
Another person here who wants tags. My use case is I have several websites that I want to change the password at regular intervals because of how sensitive they are. Think banking. But then other sites that aren't banking that also need to be changed regularly. If I could have a tag to mark all the websites that need to be changed regularly, but still be able to split things up into tags that indicate their normal category like banking, shopping, etc... that would simplify my life. Could easily find the sites when its time to change them. and find them normally by their banking/shopping tags.

**Comment by clemwo** [comment]
I think the case for tags or labels has been made already. I desperately want this. Is there a way to donate to support the development of this feature?  
I love bitwarden but to me it is a shame that there is no way to tag an item

**Comment by eliykat** [comment]
Please vote for tags here: https://community.bitwarden.com/t/tagging-items-in-vault/132/7 and not in this thread.
