### ISSUE TITLE
Suggestion: Add option to use sequence of english words for generated passwords.

### ISSUE THREAD

**Issue by mjlm** [bitwarden/core#93]
First of all, thanks for developing bitwarden!

Suggestion: Following the logic of https://xkcd.com/936/ , it would be great to be able to generate passwords that are a concatenation of real words from a (large) dictionary. 

Obviously, with a password manager, it is not necessary to remember passwords. But it is sometimes necessary to copy a password manually, which would be much easier with real words than random letters. Also, it is easier to type real words on a phone keyboard than sequences with special characters.

**Comment by kspearrin** [comment]
This has been on our backlog for some time now.

**Comment by ghisvail** [comment]
There is a program called `xkcdpass` which does exactly that.

**Comment by huuhaa** [comment]
Could xkcdpass be used with bitwarden? It seems already have some language support...

https://github.com/redacted/XKCD-password-generator

And also, please enable usage of this feature already when creating account / changing master password.

**Comment by jnv** [comment]
Also take a look at [Enpass](https://www.enpass.io/)' pronounceable passwords generator, which lets you choose separator, add uppercase and digits:

![enpass password generator](https://user-images.githubusercontent.com/616767/34977647-a634a0be-fa9b-11e7-8668-71405064cb93.png)

There are also [passphrase generators for KeePass](https://keepass.info/plugins.html#ppgen).

**Comment by ple103** [comment]
We could also consider MasterPassX ([demo](https://masterpassx.cretezy.com/#) | [source](https://github.com/Cretezy/MasterPassX)). Given an input, it will produce a pass phrase amongst other things like PINs, passwords, and pronounceable gibberish word.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
